# Generated by Django 4.2.27 on 2026-01-21 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('about', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=255)),
                ('accuracy', models.IntegerField()),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.master')),
            ],
        ),
    ]
