# Generated by Django 4.2.27 on 2026-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_masteravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
