# Generated by Django 4.2.27 on 2026-02-02 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_master_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
