# Generated by Django 4.2.27 on 2026-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
