# Generated by Django 4.2.27 on 2026-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='service_type',
            field=models.CharField(choices=[('barber', 'Barber'), ('beard', 'Beard'), ('haircut', 'Haircut')], default='barber', max_length=20),
        ),
    ]
