# Generated by Django 4.2.27 on 2026-02-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_master_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlocation',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_location', to='core.master'),
        ),
    ]
