# Generated by Django 4.2.27 on 2026-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_masterlocation_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='master',
            name='service_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='master',
            name='service_type',
            field=models.CharField(choices=[('barber', 'Barber'), ('beard', 'Beard'), ('haircut', 'Haircut'), ('planting', 'Planting')], default='barber', max_length=20),
        ),
    ]
